import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const SESSION_LABELS = { A: 'A', B: 'B', C: 'C' };
function prettySlot3(program, key) {
    const slot = program.coreFinisher.slots.find((s) => s.rotates);
    return slot?.options.find((o) => o.key === key)?.name ?? key;
}
export function Hero({ program, rec, onStart, }) {
    const next = program.workouts[rec.nextSession];
    return (_jsxs("section", { className: "rounded-2xl border border-line bg-surface p-5", children: [_jsx("div", { className: "text-xs font-semibold uppercase tracking-widest text-accent", children: "Next session" }), _jsxs("div", { className: "mt-1 flex items-baseline gap-3", children: [_jsx("span", { className: "text-5xl font-bold leading-none", children: SESSION_LABELS[rec.nextSession] }), _jsx("span", { className: "text-base text-slate-300", children: next.name.replace(/^Session [ABC] — /, '') })] }), _jsx("p", { className: "mt-2 text-sm text-slate-400", children: rec.reason }), rec.warnings.map((w, i) => (_jsxs("p", { className: "mt-2 rounded-lg bg-amber-500/10 px-3 py-2 text-sm text-amber-300", children: ["\u26A0\uFE0F ", w] }, i))), _jsxs("button", { onClick: () => onStart(rec.nextSession), className: "mt-4 w-full rounded-xl bg-accent py-3 text-center font-semibold text-bg active:bg-accentDim", children: ["Start Session ", SESSION_LABELS[rec.nextSession]] }), _jsxs("div", { className: "mt-4 space-y-1 border-t border-line pt-3 text-sm text-slate-400", children: [rec.nextSession === 'C' && rec.cTypeNext && (_jsxs("div", { className: "flex justify-between", children: [_jsx("span", { children: "Conditioning type" }), _jsx("span", { className: "text-slate-200", children: program.workouts.C.alternates.find((a) => a.key === rec.cTypeNext)?.label ?? rec.cTypeNext })] })), _jsxs("div", { className: "flex justify-between", children: [_jsx("span", { children: "Core slot-3" }), _jsx("span", { className: "text-slate-200", children: prettySlot3(program, rec.slot3Next) })] }), rec.legAppend && (_jsxs("div", { className: "flex justify-between text-amber-300", children: [_jsx("span", { children: "Leg append" }), _jsx("span", { children: "Squat 2\u00D75 + RDL 2\u00D78" })] }))] }), _jsxs("div", { className: "mt-4", children: [_jsx("div", { className: "mb-1 text-xs text-slate-500", children: "Or pick manually" }), _jsx("div", { className: "grid grid-cols-3 gap-2", children: ['A', 'B', 'C'].map((s) => (_jsx("button", { onClick: () => onStart(s), className: `rounded-xl border py-2 font-medium ${s === rec.nextSession ? 'border-accent text-accent' : 'border-line text-slate-300'}`, children: s }, s))) })] })] }));
}
