import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from 'react';
import { ExerciseItem } from './ExerciseItem';
function SectionTitle({ children, hint }) {
    return (_jsxs("div", { className: "mb-2 mt-5 flex items-baseline justify-between", children: [_jsx("h3", { className: "text-sm font-bold uppercase tracking-widest text-slate-400", children: children }), hint && _jsx("span", { className: "text-xs text-slate-500", children: hint })] }));
}
export function WorkoutView({ program, session, cType, slot3Next, legAppend, onPlay, onBack, onFinish, }) {
    const [t1Only, setT1Only] = useState(false);
    const workout = program.workouts[session];
    const keepTier = (tier) => !t1Only || tier === 'T1';
    return (_jsxs("div", { className: "pb-28", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("button", { onClick: onBack, className: "text-sm text-slate-400", children: "\u2190 Home" }), _jsxs("label", { className: "flex items-center gap-2 text-sm text-slate-300", children: [_jsx("input", { type: "checkbox", checked: t1Only, onChange: (e) => setT1Only(e.target.checked) }), "T1 only"] })] }), _jsx("h1", { className: "mt-2 text-2xl font-bold", children: workout.name }), workout.note && _jsx("p", { className: "mt-1 text-sm text-slate-400", children: workout.note }), _jsx(SectionTitle, { hint: program.athleticPrep.note ? undefined : undefined, children: program.athleticPrep.title }), _jsx("div", { className: "space-y-2", children: program.athleticPrep.items.filter((i) => keepTier(i.tier)).map((i, idx) => (_jsx(ExerciseItem, { item: i, onPlay: onPlay }, idx))) }), _jsx(SectionTitle, { children: "Main work" }), workout.type === 'strength' ? (_jsx("div", { className: "space-y-2", children: workout.items.filter((i) => keepTier(i.tier)).map((i, idx) => (_jsx(ExerciseItem, { item: i, onPlay: onPlay }, idx))) })) : (_jsxs("div", { className: "space-y-2", children: [workout.warmup && keepTier(workout.warmup.tier) && (_jsx(ExerciseItem, { item: workout.warmup, onPlay: onPlay })), workout.alternates.map((alt) => {
                        const isToday = alt.key === (cType ?? workout.alternates[0]?.key);
                        return (_jsxs("div", { className: `rounded-xl border p-3 ${isToday ? 'border-accent bg-surface' : 'border-line bg-surface/50 opacity-60'}`, children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "font-medium text-slate-100", children: alt.label }), isToday && _jsx("span", { className: "text-xs font-semibold text-accent", children: "TODAY" })] }), _jsx("div", { className: "mt-1 text-sm text-slate-300", children: alt.main }), alt.note && _jsx("div", { className: "mt-1 text-xs text-slate-500", children: alt.note })] }, alt.key));
                    }), legAppend && (_jsxs("div", { className: "rounded-xl border border-amber-500/40 bg-amber-500/10 p-3 text-sm text-amber-200", children: ["Leg append (two futsal weeks): ", _jsx("b", { children: "Squat 2\u00D75 + RDL 2\u00D78" })] })), workout.cooldown && keepTier(workout.cooldown.tier) && (_jsx(ExerciseItem, { item: workout.cooldown, onPlay: onPlay }))] })), _jsx(SectionTitle, { hint: "T1 \u00B7 never cut", children: program.coreFinisher.title }), _jsx("div", { className: "space-y-2", children: program.coreFinisher.slots.map((slot) => {
                    const current = slot.rotates ? slot.options.find((o) => o.key === slot3Next) : null;
                    return (_jsxs("div", { className: "rounded-xl border border-line bg-surface p-3", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("span", { className: "font-medium text-slate-100", children: [slot.slot, ". ", slot.label] }), slot.reps && _jsx("span", { className: "text-sm text-slate-300", children: slot.reps })] }), _jsx("div", { className: "mt-1 text-sm text-slate-300", children: slot.rotates ? (_jsxs(_Fragment, { children: [_jsx("span", { className: "font-medium text-accent", children: current?.name ?? slot3Next }), _jsxs("span", { className: "text-slate-500", children: [' ', "(today) \u00B7 ", slot.options.filter((o) => o.key !== slot3Next).map((o) => o.name).join(' / ')] })] })) : (slot.options.map((o) => o.name).join(' or ')) }), slot.note && _jsx("div", { className: "mt-1 text-xs text-slate-500", children: slot.note })] }, slot.slot));
                }) }), _jsx("div", { className: "safe-bottom fixed inset-x-0 bottom-0 border-t border-line bg-bg/90 p-3 backdrop-blur", children: _jsx("button", { onClick: onFinish, className: "mx-auto block w-full max-w-md rounded-xl bg-accent py-3 font-semibold text-bg active:bg-accentDim", children: "I finished the training" }) })] }));
}
